# Testing environment for AIOHappyBase
FROM dajobe/hbase:latest

RUN apt-get update
RUN apt-get install -y 'python3.6' 'python3.7' 'python3.8' 'python3.6-dev' 'python3.7-dev' 'python3.8-dev' python3-pip net-tools git
